"""Add damage column to Spell

Revision ID: 40ae25403ca6
Revises: adc6326afdf4
Create Date: 2023-08-12 13:16:58.055341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40ae25403ca6'
down_revision: Union[str, None] = 'adc6326afdf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spell', sa.Column('damage', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spell', 'damage')
    # ### end Alembic commands ###
