"""Add Spell class

Revision ID: 4ff7cb7b42c6
Revises: 
Create Date: 2023-08-11 11:23:24.018103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ff7cb7b42c6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spell',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('casting_level', sa.Integer(), nullable=False),
    sa.Column('components', sa.String(), nullable=True),
    sa.Column('range', sa.String(), nullable=True),
    sa.Column('material', sa.String(), nullable=True),
    sa.Column('ritual', sa.Integer(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('concentration', sa.Integer(), nullable=True),
    sa.Column('casting_time', sa.String(), nullable=True),
    sa.Column('damage_type', sa.String(), nullable=True),
    sa.Column('school', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spell')
    # ### end Alembic commands ###
