"""add classes column to spell

Revision ID: bc66399bf3b3
Revises: 2cea16d7e311
Create Date: 2023-08-12 15:58:09.127482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc66399bf3b3'
down_revision: Union[str, None] = '2cea16d7e311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spell', sa.Column('classes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spell', 'classes')
    # ### end Alembic commands ###
