"""Add higher_level column

Revision ID: eacb401f1309
Revises: 59f1248db5b9
Create Date: 2023-08-11 20:13:19.620526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eacb401f1309'
down_revision: Union[str, None] = '59f1248db5b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spell', sa.Column('higher_level', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spell', 'higher_level')
    # ### end Alembic commands ###
